---
require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe

Metrics/LineLength:
  Exclude:
    - telegram-bot-ruby.gemspec
    - examples/*.rb
